# Generated by Django 3.2.16 on 2022-10-16 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Torrent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('torrent_link', models.TextField(blank=True, null=True)),
                ('img_link', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.CharField(blank=True, max_length=255, null=True)),
                ('path', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('genrue_id', models.IntegerField(default=1)),
                ('genrue_name', models.CharField(blank=True, max_length=255, null=True)),
                ('author_id', models.IntegerField(null=True)),
                ('story_by', models.CharField(blank=True, max_length=255, null=True)),
                ('art_by', models.CharField(blank=True, max_length=255, null=True)),
                ('book_id', models.IntegerField(null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True)),
                ('volume', models.IntegerField(null=True)),
                ('book_name', models.CharField(blank=True, max_length=255, null=True)),
                ('save_path', models.CharField(blank=True, max_length=255, null=True)),
                ('exist_flg', models.BooleanField()),
            ],
        ),
    ]
